[project]
name = "churn-prediction-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11, <3.14"
dependencies = [
    "joblib>=1.5.3",
    "litestar[standard]>=2.21.1",
    "pydantic>=2.13.4",
    "scikit-learn==1.6.1",
    "pandas ==2.2.3",
    "axiom-py>=0.10.0",
    "python-dotenv>=1.2.2",
    "locust>=2.44.0",
]

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
    "pytest>=9.0.3",
    "pytest-cov>=7.1.0",
    "ruff>=0.15.12",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
